# Generated by Django 4.2 on 2023-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UFTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uf',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
